console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
terminal_background = 'p:t-background'
version = 3
auto_upgrade = true
final_space = true

[palette]
blue-bell = '#9aa5ce'
blue-black = '#565f89'
celeste-blue = '#b4f9f8'
light-sky-blue = '#7dcfff'
main-bg = 'transparent'
pastal-grey = '#cfc9c2'
pistachio-green = '#9ece6a'
t-background = 'p:main-bg'
terminal-black = 'black'
terminal-blue = '#7aa2f7'
terminal-green = '#73daca'
terminal-magenta = '#bb9af7'
terminal-red = '#f7768e'
terminal-white = '#c0caf5'
terminal-yellow = '#e0af68'
white-blue = '#a9b1d6'

[secondary_prompt]
template = '➜ '
foreground = 'p:terminal-blue'
background = 'transparent'

[transient_prompt]
template = '➜ '
foreground = 'p:terminal-blue'
background = 'p:t-background'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
style = 'plain'
template = '➜ '
foreground = 'p:terminal-blue'
background = 'transparent'
type = 'text'

[[blocks.segments]]
style = 'plain'
template = '<b>{{ .Path }}</b>'
foreground = 'p:terminal-magenta'
background = ''
type = 'path'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
style = 'plain'
foreground = 'p:light-sky-blue'
background = ''
type = 'git'
foreground_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}',
  '{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}',
  '{{ if gt .Behind 0 }}p:celeste-blue{{ end }}',
]

[blocks.segments.properties]
branch_ahead_icon = '⇡ '
branch_behind_icon = '⇣ '
branch_gone_icon = '󱓊 '
branch_icon = ' '
fetch_status = true
github_icon = ' '

[[blocks.segments]]
style = 'plain'
template = '  {{ .FormattedMs }} '
foreground = 'p:terminal-blue'
background = ''
type = 'executiontime'

[blocks.segments.properties]
style = 'austin'
threshold = 500

[[blocks.segments]]
style = 'plain'
template = ' '
foreground = 'p:terminal-red'
background = ''
type = 'status'

[[blocks]]
type = 'prompt'
alignment = 'right'
overflow = 'hide'

[[blocks.segments]]
style = 'plain'
template = ' {{ .Full }} '
foreground = 'p:pistachio-green'
background = ''
type = 'node'

[[blocks.segments]]
style = 'plain'
foreground = 'p:terminal-yellow'
background = ''
type = 'pnpm'

[[blocks.segments]]
style = 'plain'
foreground = 'p:terminal-magenta'
background = ''
type = 'npm'

[[blocks.segments]]
style = 'plain'
template = '󱘗 {{ .Full }}'
foreground = 'p:terminal-red'
background = ''
type = 'rust'

[[blocks.segments]]
style = 'plain'
template = ' {{ .Full }} '
foreground = 'p:terminal-blue'
background = ''
type = 'php'

[[blocks.segments]]
style = 'plain'
template = ' {{ .Full }}'
foreground = 'p:terminal-yellow'
background = ''
type = 'python'

[[blocks.segments]]
style = 'plain'
template = ' {{ .Full }}'
foreground = 'p:terminal-magenta'
background = ''
type = 'julia'

[[blocks.segments]]
style = 'plain'
template = ' {{ .Full }}'
foreground = 'p:terminal-red'
background = ''
type = 'ruby'

[[blocks.segments]]
style = 'plain'
template = ' {{ .Full }}'
foreground = 'p:light-sky-blue'
background = ''
type = 'go'

[[blocks.segments]]
style = 'plain'
template = ' {{ if .Version }} {{.Version}}{{ end }}'
foreground = 'p:terminal-yellow'
background = ''
type = 'project'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
style = 'plain'
template = '▶'
foreground = 'p:pistachio-green'
background = ''
type = 'text'
